name: Build SkyWars

on:
  push:
    branches: [main]

concurrency: skywars_main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set the Build number
        id: calculated_build_number
        env:
          NUM: ${{ github.run_number }}
        run: echo "build_n=$(($NUM+40))" >> $GITHUB_OUTPUT
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_NUMBER: ${{ steps.calculated_build_number.outputs.build_n }}
      - name: Upload the final artifact
        uses: actions/upload-artifact@v4
        with:
          path: plugin/build/libs/BedWars*[!s].jar
